FROM node:24-alpine AS builder
WORKDIR /app
COPY package*.json .
RUN npm install
COPY . .
RUN npm run build

FROM nginx:1.27-alpine
COPY --from=builder /app/build/ /usr/share/nginx/html
COPY --from=builder /app/nginx.conf /etc/nginx/templates/cms.conf.template