version: '3.8'

services:
  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
    env_file: .env

  backend:
    build: ./backend
    ports:
      - 3001:3001
    env_file: .env
    command: ./docker-entrypoint.sh
    volumes:
      - uploads:/app/data/uploads
      - logs:/app/data/logs

volumes:
  cms:
  uploads:
  logs:
