
services:
  frontend:
    depends_on:
      - backend
    build: ./frontend
    ports:
      - 3000:3000
    env_file: ./frontend/.env
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules
  backend:
    build: ./backend
    ports:
      - 3001:3001
    env_file: ./backend/.env
    command: ./docker-entrypoint.sh
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/data/uploads:/app/data/uploads
      - ./backend/data/logs:/app/data/logs
