version: '3.8'

services:
  frontend:
    depends_on:
      - backend
    build: ./frontend
    ports:
      - 3000:3000
    env_file: ./frontend/.env
    volumes:
      - ./frontend/src:/app/src
  backend:
    build: ./backend
    ports:
      - 3001:3001
    env_file: ./backend/.env
    environment:
      DATABASE_URL: postgresql://postgres:eC*vtL*DJ7pLw-p@db.ppcubyilaktvllezdzkw.supabase.co:5432/postgres
    command: ./docker-entrypoint.sh
    volumes:
      - ./backend:/app
      - ./backend/data/uploads:/app/data/uploads
      - ./backend/data/logs:/app/data/logs
