version: '3.8'

services:
  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
    env_file: .env

  backend:
    depends_on:
      - db
    build: ./backend
    ports:
      - 3001:3001
    env_file: .env
    environment:
      DB_URL: mongodb://db/cms
    command: ./docker-entrypoint.sh
    volumes:
      - uploads:/app/data/uploads
      - logs:/app/data/logs

  db:
    image: mongo:5.0.5-focal
    ports:
      - 27017:27017
    volumes:
      - cms_db:/data/db

volumes:
  cms:
  uploads:
  logs:
